<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

---

# Date & Time Filtering

### 🥅 Analysis Goals

- **Aggregate sales by specific date components**: Extract and group data by year, month, and day using `DATE_PART` for detailed time-based analyses.  
- **Filter data based on the current date**: Use `CURRENT_DATE` to dynamically filter results for reports.

- `DATE_PART()` & `EXTRACT()`
- `CURRENT_DATE()` & `NOW()`

[Source Documentation on Date/Time Functions.](https://www.postgresql.org/docs/current/functions-datetime.html)

In [11]:
%%sql

SELECT
    orderdate,
    DATE_PART('year', orderdate) AS order_year,
    DATE_PART('month', orderdate) AS order_month,
    DATE_PART('day', orderdate) AS order_day
FROM
    sales
ORDER BY RANDOM()
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  order_year  order_month  order_day
0  2018-10-12     2018.00        10.00      12.00
1  2019-11-23     2019.00        11.00      23.00
2  2017-09-21     2017.00         9.00      21.00
3  2021-10-27     2021.00        10.00      27.00
4  2023-12-16     2023.00        12.00      16.00
5  2018-03-30     2018.00         3.00      30.00
6  2023-04-25     2023.00         4.00      25.00
7  2015-01-22     2015.00         1.00      22.00
8  2022-09-01     2022.00         9.00       1.00
9  2022-10-27     2022.00        10.00      27.00

#### `EXTRACT`

- `EXTRACT()` is a more verbose way to extract specific components from a date or timestamp.

  ```sql
  EXTRACT(unit FROM source)
  ```
- Common units:
  - `YEAR`
  - `MONTH`
  - `DAY`
  - `HOUR`
  - `MINUTE`
  - `SECOND`

In [10]:
%%sql

SELECT
    orderdate,
    EXTRACT(YEAR FROM orderdate) AS extract_year,
    EXTRACT(MONTH FROM orderdate) AS extract_month,
    EXTRACT(DAY FROM orderdate) AS extract_day
FROM
    sales
ORDER BY RANDOM()
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate extract_year extract_month extract_day
0  2019-01-26         2019             1          26
1  2018-06-09         2018             6           9
2  2016-07-28         2016             7          28
3  2021-09-24         2021             9          24
4  2021-12-01         2021            12           1
5  2023-06-29         2023             6          29
6  2021-01-28         2021             1          28
7  2016-01-26         2016             1          26
8  2019-02-13         2019             2          13
9  2018-12-07         2018            12           7

#### Difference between `DATE_PART` and `EXTRACT`

| Feature               | Definition                               | Syntax                                | Example Query                                   | Example Output       |
|-----------------------|------------------------------------------|---------------------------------------|------------------------------------------------|----------------------|
| **`DATE_PART`**         | Retrieves part of a date as a string input. | `DATE_PART('field', source)`          | `DATE_PART('month', TIMESTAMP '2025-01-10')`   | `1.0` (double precision) |
| **`EXTRACT`**           | Retrieves part of a date using a keyword. | `EXTRACT(field FROM source)`          | `EXTRACT(MONTH FROM TIMESTAMP '2025-01-10')`   | `1` (integer)         |

In [13]:
%%sql

SELECT
    EXTRACT(YEAR FROM orderdate) AS order_year,
    EXTRACT(MONTH FROM orderdate) AS order_month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
FROM
    sales
GROUP BY
    order_year,
    order_month
ORDER BY
    order_year,
    order_month;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue
0         2015           1    384092.66
1         2015           2    706374.12
2         2015           3    332961.59
3         2015           4    160767.00
4         2015           5    548632.63
..         ...         ...          ...
107       2023          12   2928550.93
108       2024           1   2677498.55
109       2024           2   3542322.55
110       2024           3   1692854.89
111       2024           4    483851.39

[112 rows x 3 columns]

---
## CURRENT_DATE & NOW

### `CURRENT_DATE`

- Retrieves the current date based on the system's time zone.

- Syntax:
    ```sql
    CURRENT_DATE
    ```

In [21]:
%%sql

SELECT
    NOW() AS current_time;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

                      current_time
0 2026-03-04 07:30:20.578467+00:00

In [25]:
%%sql

SELECT
    s.orderdate,
    p.categoryname,
    SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM
    sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
    EXTRACT(YEAR FROM s.orderdate) >= EXTRACT(YEAR FROM CURRENT_DATE) - 5
GROUP BY
    s.orderdate,
    p.categoryname
ORDER BY
    s.orderdate,
    p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

       orderdate                   categoryname  net_revenue
0     2021-01-01                          Audio      1206.67
1     2021-01-01        Cameras and camcorders       2228.75
2     2021-01-01                    Cell phones     10582.00
3     2021-01-01                      Computers     12718.95
4     2021-01-01                 Games and Toys       235.53
...          ...                            ...          ...
8952  2024-04-20                      Computers     58353.68
8953  2024-04-20                 Games and Toys      1744.30
8954  2024-04-20                Home Appliances      1562.04
8955  2024-04-20  Music, Movies and Audio Books      4949.43
8956  2024-04-20                   TV and Video      9841.91

[8957 rows x 3 columns]