<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

# Ranking Functions

- **Running Order & Avg Revenue:** Get the running order and average revenue for each order.
- **Rank Customers by Order Quantity:** Calculate and rank customers based on their total order quantity. Provides meaningful sequence of orders within each day.
- `ORDER BY`
- Ranking
    - `ROW_NUMBER`
    - `RANK`
    - `DENSE_RANK`

---
## ORDER BY
- **ORDER BY**: Orders rows within each partition for the function.
- `ORDER BY` can be ordered in either `DESC` or `ASC` order.
- Syntax
    ```sql
    SELECT
        window_function() OVER (
            PARTITION BY partition_expression
            ORDER BY column_name --DESC or ASC
        ) AS window_column_alias
    FROM table_name;
    ```

- Get the running order count for each order.
- Calculate the running average revenue for each order.

In [5]:
%%sql

SELECT
    customerkey,
    orderdate,
    (quantity * netprice * exchangerate) AS net_revenue,
    COUNT(*) OVER (
      PARTITION BY customerkey
      ORDER BY orderdate
    ) AS running_order_count
FROM
    sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        customerkey   orderdate  net_revenue  running_order_count
0                15  2021-03-08      2217.41                    1
1               180  2018-07-28       525.31                    1
2               180  2023-08-28        71.36                    3
3               180  2023-08-28      1913.55                    3
4               185  2019-06-01      1395.52                    1
...             ...         ...          ...                  ...
199868      2099711  2016-08-13      2067.75                    1
199869      2099711  2017-08-14      3940.92                    2
199870      2099743  2022-03-17       375.57                    2
199871      2099743  2022-03-17        94.05                    2
199872      2099743  2023-02-11       598.46                    3

[199873 rows x 4 columns]

#### Running Average Net Revenue for Customer

**`ORDER BY`**

1. Get the running order count that's ordered by `orderdate` using `ORDER BY` in the windows function.
    - Get net revenue per order `(quantity * netprice * exchangerate)`
    - Calculate the running average revenue using `AVG(*) OVER (PARTITION BY customerkey ORDER BY orderdate) AS running_order_count`
    - Order the running count by `orderdate` for each customer

In [8]:
%%sql

SELECT
    customerkey,
    orderdate,
    (quantity * netprice * exchangerate) AS net_revenue,
    COUNT(*) OVER (
      PARTITION BY customerkey
      ORDER BY orderdate
    ) AS running_order_count,
    AVG((quantity * netprice * exchangerate)) OVER (
      PARTITION BY customerkey
      ORDER BY orderdate
    ) AS running_avg_revenue
FROM
    sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_avg_revenue
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,71.36,3,836.74
3,180,2023-08-28,1913.55,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
...,...,...,...,...,...
199868,2099711,2016-08-13,2067.75,1,2067.75
199869,2099711,2017-08-14,3940.92,2,3004.34
199870,2099743,2022-03-17,375.57,2,234.81
199871,2099743,2022-03-17,94.05,2,234.81
199872,2099743,2023-02-11,598.46,3,356.03

---
## ROW_NUMBER
- **ROW NUMBER**: Assigns a unique number to each row within a partition.
- Syntax:
    ```sql
    ROW_NUMBER() OVER(
         PARTITION BY partition_expression
         ORDER BY column_name
    ) AS window_column_alias
    ```
    #### Assign Row Numbers Without ORDER BY (DEMO ONLY)

1. Assign a row number to each row in the sales table.
   - Use ROW_NUMBER() without any ORDER BY clause.
      - ⚠️ This will assign arbitrary numbers that may change between query runs.
   - Not recommended as it provides no meaningful sequence.

In [17]:
%%sql

SELECT
    ROW_NUMBER() OVER(
      ORDER BY
          orderdate,
          orderkey,
          linenumber
    ) AS row_number,
    *
FROM
    sales
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_number,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,6,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,7,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,8,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,9,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,10,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

#### Assign Daily Order Numbers With PARTITION BY

1. Assign a row number to each row in the sales table, partitioned by date.
   - Use `ROW_NUMBER()` with `PARTITION BY orderdate` and `ORDER BY orderdate, orderkey, linenumber`.
      - ✅ This will assign numbers that restart each day, ordered by order ID and line number.
   - Provides meaningful sequence of orders within each day.
   - WHERE clause included to show orders from the next day, demonstrating how numbering restarts.

In [18]:
%%sql

SELECT
    ROW_NUMBER() OVER(
      ORDER BY
          orderdate,
          orderkey,
          linenumber
    ) AS row_number,
    *
FROM
    sales
WHERE
    orderdate > '2015-01-01'
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_number,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
1,2,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
2,3,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
3,4,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
4,5,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
5,6,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
6,7,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
7,8,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
8,9,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
9,10,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00

#### Rank Customers Order Quantity

**`ROW_NUMBER`**

1. By customer, assign a rank to the total orders each customer made.  
   - Use `COUNT(orderkey)` to calculate the total number of orders for each customer.  
   - Group by `customerkey` to ensure the order count is calculated for each individual customer.  
   - Use `ROW_NUMBER() OVER (ORDER BY COUNT(orderkey) DESC)` to assign a unique rank to each customer based on their total orders, in descending order.  
   - Select `customerkey`, `total_orders`, and the rank (`row_number_rank`) in the output.

In [19]:
%%sql

SELECT
    customerkey,
    COUNT(orderkey) AS total_orders,
    ROW_NUMBER() OVER (ORDER BY COUNT(orderkey) DESC) AS total_orders_row_num
FROM
    sales
GROUP BY
    customerkey
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey  total_orders  total_orders_row_num
0      1834524            31                     1
1      1375597            30                     2
2       249557            27                     3
3       459519            26                     4
4      1495941            26                     5
5      1801215            26                     6
6      1219056            25                     7
7       759419            24                     8
8      1427444            24                     9
9      1876222            24                    10

---
## RANK
- **RANK**: Assigns the same rank to rows with identical values but skips ranks after ties (e.g., 1, 2, 2, 4).
- Syntax:
    ```sql
    RANK() OVER(
         PARTITION BY partition_expression
         ORDER BY column_name
    ) AS window_column_alias
    ```

#### Rank Customers Order Quantity

**`RANK`**

1. By customer, assign a rank to the total orders each customer made (from the previous example use `RANK` instead).  
   - Use `COUNT(orderkey)` to calculate the total number of orders for each customer.  
   - Group by `customerkey` to ensure the order count is calculated for each individual customer.  
   - 🔔 Use `RANK() OVER (ORDER BY COUNT(orderkey) DESC)` to assign a unique rank to each customer based on their total orders, in descending order.  
   - Select `customerkey`, `total_orders`, and the rank (`rank_rank`) in the output.

In [22]:
%%sql

SELECT
    customerkey,
    COUNT(*) AS total_orders,
    ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS total_orders_row_num,
    RANK() OVER (ORDER BY COUNT(*) DESC) AS total_orders_rank
FROM
    sales
GROUP BY customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey  total_orders  total_orders_row_num  total_orders_rank
0          1834524            31                     1                  1
1          1375597            30                     2                  2
2           249557            27                     3                  3
3           459519            26                     4                  4
4          1495941            26                     5                  4
...            ...           ...                   ...                ...
49482      1448235             1                 49483              39985
49483        89802             1                 49484              39985
49484       675412             1                 49485              39985
49485       638307             1                 49486              39985
49486       618309             1                 49487              39985

[49487 rows x 4 columns]

---
## DENSE RANK
- **DENSE_RANK**: Similar to RANK(), it assigns the same rank to rows with identical values but does not skip ranks after ties (e.g., 1, 2, 2, 3).
- Syntax:
    ```sql
    DENSE_RANK() OVER(
         PARTITION BY partition_expression
         ORDER BY column_name
    ) AS window_column_alias
    ```
    #### Rank Customers Order Quantity

**`DENSE_RANK`**

1. By customer, assign a rank to the total orders each customer made (from the previous example use `DENSE_RANK` instead).  
   - Use `COUNT(orderkey)` to calculate the total number of orders for each customer.  
   - Group by `customerkey` to ensure the order count is calculated for each individual customer.  
   - 🔔 Use `DENSE_RANK() OVER (ORDER BY COUNT(orderkey) DESC)` to assign a unique rank to each customer based on their total orders, in descending order.  
   - Select `customerkey`, `total_orders`, and the rank (`dense_rank`) in the output.

In [23]:
%%sql

SELECT
    customerkey,
    COUNT(*) AS total_orders,
    ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS total_orders_row_num,
    RANK() OVER (ORDER BY COUNT(*) DESC) AS total_orders_rank,
    DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS total_orders_dense_rank
FROM
    sales
GROUP BY customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

,customerkey,total_orders,total_orders_row_num,total_orders_rank,total_orders_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
...,...,...,...,...,...
49482,1448235,1,49483,39985,28
49483,89802,1,49484,39985,28
49484,675412,1,49485,39985,28
49485,638307,1,49486,39985,28
49486,618309,1,49487,39985,28

### 💡 What's the difference between `ROW_NUMBER()`, `RANK()`, `DENSE_RANK()`

1. `ROW_NUMBER()`
    - Even if two rows have the same value, they will get different, consecutive ranks.
    - Example: If three products have the same sales amount, they’ll be ranked 1, 2, and 3 in sequence.

| Sales | ROW_NUMBER() |
|-------|--------------|
| 500   | 1            |
| 500   | 2            |
| 400   | 3            |
| 300   | 4            |  
  

2. `RANK()`
    - Rows with identical values receive the same rank, and the next rank jumps to the next number in sequence.
    - Example: If three products have the same highest sales amount, they all get rank 1, and the next product will get rank 4.

| Sales | ROW_NUMBER() |
|-------|--------------|
| 500   | 1            |
| 500   | 1            |
| 400   | 3            |
| 300   | 4            |


3. `DENSE_RANK()`
    - Rows with identical values receive the same rank, and the next rank continues sequentially without gaps.
    - Example: If three products have the same highest sales amount, they all get rank 1, and the next product will get rank 2.

| Sales | ROW_NUMBER() |
|-------|--------------|
| 500   | 1            |
| 500   | 1            |
| 400   | 2            |
| 300   | 3            |